name: Deploy to EC2

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST_NAME }}
          username: ${{ secrets.EC2_USER_NAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd terraform-v2/docker-nestjs-nextjs-demo
            git checkout feature/nuxt-ec2
            docker compose up -d --build
